import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./[locale]/globals.css";
import Navbar from "@/src/components/Navbar";
import { Suspense } from "react";
import Loading from "./[locale]/product/loading";
import { NextIntlClientProvider } from "next-intl";
import Image from "next/image";
import img2 from '../../public/image copy 20.png'
import img3 from '../../public/image copy 21.png'
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};
 
export default async function RootLayout({
  children,
  params,
}: Props) {
    const { locale } = await params;

  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider>
          <Suspense fallback={<Loading />}>{children}</Suspense>
          <footer className="mt-[100px] p-[20px]">
            <div className="flex items-center justify-between w-[90%] m-auto">
              <Image src={img2} alt="" />
              <div className="flex items-center gap-[20px] text-[18px]">
                <p>О нас</p>
                <p>Карта покрытия</p>
                <p>Инфраструктура</p>
                <p>Партнеры</p>
                <p>Новости</p>
                <p>Вакансии</p>
              </div>
              <Image src={img3} alt="" />
            </div>
          </footer>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}